image: node:18

stages:
  - build_and_test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - extension/node_modules/

build_extension:
  stage: build_and_test
  script:
    - node -v
    - npm -v
    - cd extension
    - npm install --progress=false
    - npm run compile
    - npm run lint
    - npm run package
  artifacts:
    name: "kuka-krl-extension-$CI_COMMIT_SHORT_SHA"
    paths:
      - extension/*.vsix
    expire_in: 1 week
  only:
    - main
