name = "kuka-krl-extension"
main = "cloudflare-worker/worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CHAT_KV"
id = "ccb4ac9320f7430592efe5816c58261c"

[[d1_databases]]
binding = "CHAT_DB"
database_name = "kuka-krl-chat-db"
database_id = "8f8b8e47-d59e-459c-8725-278ce358fddb"
