export interface EkiChannelConfig {
  name: string;
  protocol: "TCP" | "UDP";
  type: "Client" | "Server";
  ip?: string;
  port: number;
  elements: { tag: string; type: "STRING" | "INT" | "REAL" | "BOOL" }[];
}

/**
 * Validates EthernetKRL (EKI) XML Configuration File Structure.
 */
export function validateEkiXmlContent(xmlText: string): {
  valid: boolean;
  errors: string[];
  channelName?: string;
} {
  const errors: string[] = [];

  if (!xmlText.includes("<ETHERNETKRL>")) {
    errors.push("Missing root element <ETHERNETKRL>");
  }
  if (!xmlText.includes("</ETHERNETKRL>")) {
    errors.push("Missing closing root element </ETHERNETKRL>");
  }
  if (!xmlText.includes("<CONFIGURATION>")) {
    errors.push("Missing <CONFIGURATION> section");
  }

  const nameMatch =
    xmlText.match(
      /<ETHERNETKRL>\s*<CONFIGURATION>\s*<EXTERNAL>\s*<TYPE>(.*?)<\/TYPE>/i,
    ) || xmlText.match(/<CONFIGURATION>\s*<NAME>(.*?)<\/NAME>/i);

  const channelName = nameMatch ? nameMatch[1].trim() : "XmlChannel";

  if (!xmlText.includes("<RECEIVE>") && !xmlText.includes("<SEND>")) {
    errors.push("EKI XML must define at least one <RECEIVE> or <SEND> block");
  }

  return {
    valid: errors.length === 0,
    errors,
    channelName,
  };
}

/**
 * Generates ready-to-use KRL source code for EthernetKRL (EKI) initialization and data exchange.
 */
export function generateEkiKrlCode(
  channelName: string = "EKI_Channel",
): string {
  return `;====================================================
; KUKA EthernetKRL (EKI) Communication Subprogram
; Channel: ${channelName}
; Generated by LiskinLabs KRL Extension (Industrial Edition)
;====================================================
DEF ${channelName}_Handler()
   DECL EKI_STATUS RET
   DECL INT nOffset
   DECL BOOL bRet
   DECL REAL rTimeout

   ; 1. Initialize EKI Channel from XML Configuration
   RET = EKI_Init("${channelName}")
   IF (RET.Connected == FALSE) THEN
      ; EKI Init Error Handling
      HALT
   ENDIF

   ; 2. Open Socket Connection
   RET = EKI_Open("${channelName}")
   IF (RET.Connected == FALSE) THEN
      ; EKI Connection Error
      HALT
   ENDIF

   WAIT SEC 0.5

   ; 3. Example: Read String / Frame from EKI Buffer
   ; RET = EKI_GetString("${channelName}", "RobotData/Command", sBuffer[])
   ; RET = EKI_GetReal("${channelName}", "RobotData/PosTarget/X", rTargetX)

   ; 4. Example: Send Acknowledgement / Robot Position
   ; RET = EKI_SetReal("${channelName}", "RobotStatus/PosX", $POS_ACT.X)
   ; RET = EKI_Send("${channelName}", "RobotStatus")

   ; 5. Close and Clear Channel when done
   RET = EKI_Close("${channelName}")
   RET = EKI_Clear("${channelName}")
END
`;
}
